-- Bootstrap lazy.nvim
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not (vim.uv or vim.loop).fs_stat(lazypath) then
	local lazyrepo = "https://github.com/folke/lazy.nvim.git"
	local out = vim.fn.system({ "git", "clone", "--filter=blob:none", "--branch=stable", lazyrepo, lazypath })
	if vim.v.shell_error ~= 0 then
		vim.api.nvim_echo({
			{ "Failed to clone lazy.nvim:\n", "ErrorMsg" },
			{ out, "WarningMsg" },
			{ "\nPress any key to exit..." },
		}, true, {})
		vim.fn.getchar()
		os.exit(1)
	end
end
vim.opt.rtp:prepend(lazypath)

-- ---------------------------------------------------------------------------------------------------------------------
-- Plugins setup: this profile extends minimalist's plugin selection as-is
-- (import "minimalist.plugins" -- lua/omarchy/plugins/ never redeclares
-- what minimalist already declares) and swaps only the theme layer for
-- Omarchy's live system theme instead of minimalist's fixed catppuccin
-- default:
--   lua/omarchy/plugins/all-themes.lua           -- every Omarchy theme, installed but inert
--   lua/omarchy/plugins/omarchy-theme-hotreload.lua -- reacts to the OS theme switcher
--   lua/omarchy/plugins/theme.lua                -- symlink to Omarchy's current theme
--                                                    (gitignored; regenerated by
--                                                    omarchy-nvim-setup / the theme switcher)
-- lua/omarchy/plugins/ holds only those three files, so loading that
-- directory pulls in exactly them.
--
-- The full LazyVim distro is intentionally never imported (no
-- `{ "LazyVim/LazyVim", import = "lazyvim.plugins" }`): that would pull in
-- LazyVim's entire default plugin bundle (telescope, neo-tree, its own
-- keymaps/options/autocmds, ...), none of which this config wants. Omitting
-- the import is simpler and more direct than importing the full bundle and
-- then disabling each plugin individually. LazyVim/LazyVim itself is still
-- present (declared by lua/omarchy/plugins/theme.lua) purely so the
-- hot-reload logic has its opts.colorscheme convention to scan for.
-- ---------------------------------------------------------------------------------------------------------------------

-- Suppresses LazyVim's own require-order health check, which the bare
-- LazyVim/LazyVim dependency would otherwise trip: this profile never calls
-- require("lazyvim").setup(), so no LazyVim distro config/keymaps/autocmds
-- ever run.
vim.g.lazyvim_check_order = false

local lazy_loader = require("lazy_loader")
local spec = lazy_loader.load_dir("minimalist.plugins")
vim.list_extend(spec, lazy_loader.load_dir("omarchy.plugins"))

require("lazy").setup(spec)

-- lazy.nvim-specific: force-load a plugin that's otherwise deferred behind
-- an event/cmd/ft trigger.
vim.keymap.set("n", "<leader>ld", "<cmd>Lazy load nvim-dap-view<cr>", { desc = "Lazy load dap setup" })
vim.keymap.set("n", "<leader>lt", "<cmd>Lazy load neotest<cr>", { desc = "Lazy load neotest" })
vim.keymap.set("n", "<leader>lD", "<cmd>Lazy load diffview.nvim<cr>", { desc = "Lazy load diffview" })
