# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include catppuccin-mocha.conf
# END_KITTY_THEME

window_padding_width 0
window_margin_width 0

# BEGIN_KITTY_FONTS
font_family JetBrainsMono Nerd Font
# END_KITTY_FONTS

shell_integration no-cursor
macos_option_as_alt yes
undercurl_style thin-sparse
hide_window_decorations yes

include kitty-override.conf

kitty_mod ctrl+shift
map kitty_mod+plus change_font_size all +1.0
map kitty_mod+equal change_font_size all +1.0
map kitty_mod+minus change_font_size all -1.0
map kitty_mod+backspace change_font_size all 0
