# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include catppuccin-mocha.conf
# END_KITTY_THEME

window_padding_width 0
window_margin_width 0

# BEGIN_KITTY_FONTS
font_family      family="JetBrainsMono Nerd Font Regular"
bold_font        family="JetBrainsMono Nerd Font, Bold"
italic_font      family="JetBrainsMono Nerd Font, Regular Italic"
bold_italic_font family="JetBrainsMono Nerd Font, Bold Italic"
# END_KITTY_FONTS

shell_integration no-cursor
macos_option_as_alt yes
undercurl_style thin-sparse

include kitty-override.conf
