customCommands:
  - key: "D"
    description: "Update date of the latest commit to now"
    context: "commits"
    command: "git commit --amend --no-edit --date=now"
    prompts:
    - type: 'confirm'
      body: 'Are you sure you want to update the date of latest commit to now?'
  - key: "<c-a>"
    context: "commits"
    command: "git commit --amend --no-verify --no-edit"
    description: "Amend commit w/o running the pre-commit hook"
  - key: "C"
    context: "files"
    command: "zellij action new-pane --close-on-exit -- git commit"
    subprocess: false
    description: "Commit with custom script"
    loadingText: "Opening commit script"
gui:
  theme:
    activeBorderColor:
      - '#89b4fa'
      - bold
    inactiveBorderColor:
      - '#a6adc8'
    optionsTextColor:
      - '#89b4fa'
    selectedLineBgColor:
      - '#313244'
    cherryPickedCommitBgColor:
      - '#45475a'
    cherryPickedCommitFgColor:
      - '#89b4fa'
    unstagedChangesColor:
      - '#f38ba8'
    defaultFgColor:
      - '#cdd6f4'
    searchingActiveBorderColor:
      - '#f9e2af'

  authorColors:
    '*': '#b4befe'
