[mgr]
border_symbol = "│"

[indicator]
padding = { open = "█", close = "█" }

[status]
sep_left = { open = "█", close = "█" }
sep_right = { open = "█", close = "█"}
progress_label  = { fg = "#ffffff", bold = true }
progress_normal = { fg = "#a6e3a1", bg = "#45475a" }
progress_error  = { fg = "#f9e2af", bg = "#f38ba8" }

perm_type  = { fg = "#89b4fa" }
perm_read  = { fg = "#f9e2af" }
perm_write = { fg = "#f38ba8" }
perm_exec  = { fg = "#a6e3a1" }
perm_sep   = { fg = "#7f849c" }

[which]
separator = "  "

[icon]
separator_open = ""
separator_close = ""
globs = []
dirs = []
files = []
exts = []
conds = []
