import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 0
padding.y = 0

decorations = "Buttonless"
# opacity = 0.8
blur = true
# startup_mode = "Fullscreen"

option_as_alt = "Both"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }

[scrolling]
multiplier = 0
