theme = "catppuccin_mocha"

[editor]
line-number = "relative"
mouse = false
rulers = [100, 120]
cursorline = true
cursorcolumn = true
undercurl = true
default-line-ending = "lf"
auto-format = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.whitespace]
# render = "all"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
nnbsp = "␣"
tab = "→"
newline = "⏎"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.lsp]
enable = true
display-messages = true

[keys.insert]
j = { k = "normal_mode" }
C-space = ["completion"]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
ret = ["expand_selection"]
tab = ["shrink_selection"]
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]

[keys.normal.space]
"." = ["file_picker_in_current_buffer_directory"]
"i" = [":toggle lsp.display-inlay-hints"]
