[[language]]
name = "lua"
language-server =  { command = "lua-language-server"}

[[language]]
name = "typescript"
language-servers = ["typescript-language-server", "biome"]

[[language]]
name = "javascript"
language-servers = ["typescript-language-server", "biome"]

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }
